name: Build and Release Python Client

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout client repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install grpcio-tools hatch

      - name: Fetch proto files from Apache Ballista
        run: |
          git clone --depth=1 https://github.com/apache/datafusion-ballista.git /tmp/ballista
          mkdir -p pyballista/protosrc
          cp /tmp/ballista/ballista/core/proto/*.proto pyballista/protosrc/

      - name: Compile proto files
        run: |
          mkdir -p pyballista/proto
          touch pyballista/proto/__init__.py
          python -m grpc_tools.protoc \
            -I pyballista/protosrc \
            --python_out=pyballista/proto \
            --grpc_python_out=pyballista/proto \
            pyballista/protosrc/ballista.proto \
            pyballista/protosrc/datafusion.proto
          echo "Listing compiled files:"
          ls -l pyballista/proto

      - name: Fix relative imports in *_pb2 and *_pb2_grpc
        run: |
          sed -i 's/^import \(.*_pb2\)/from . import \1/' pyballista/proto/*_pb2*.py


      - name: Build package
        run: hatch build

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          files: dist/*.whl
